In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("heart-disease.csv")

In [4]:
df.sample(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
188,63,1,0,130,254,0,0,147,0,1.4,1,1,3,0
313,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
786,67,1,0,125,254,1,1,163,0,0.2,1,2,3,0
173,39,0,2,94,199,0,1,179,0,0.0,2,0,2,1
140,57,1,0,152,274,0,1,88,1,1.2,1,1,3,0
557,48,1,0,122,222,0,0,186,0,0.0,2,0,2,1
783,56,1,1,120,240,0,1,169,0,0.0,0,0,2,1
943,65,1,0,120,177,0,1,140,0,0.4,2,0,3,1
72,56,1,0,125,249,1,0,144,1,1.2,1,1,2,0
551,54,1,0,122,286,0,0,116,1,3.2,1,2,2,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [6]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [7]:
focus=df.iloc[:,3:5]
focus

      trestbps  chol
0          125   212
1          140   203
2          145   174
3          148   203
4          138   294
...        ...   ...
1020       140   221
1021       125   258
1022       110   275
1023       110   254
1024       120   188

[1025 rows x 2 columns]

In [10]:
column= focus.to_numpy().sum(axis=0)
column
focus['trestbps'][0]

np.int64(125)

In [41]:
focus=focus.to_numpy()

In [42]:
total_sum=np.sum(column)
total_sum

np.int64(387052)

In [ ]:
chi_score=0
total_sum=np.sum(column)
for i in range(focus.shape[0]):
    row_sum=focus['trestbps'][i][0]+focus[i][1]
    ex1=(row_sum*column[0])/total_sum
    ex2=(row_sum*column[1])/total_sum
    chi_score+=(((focus[i][0]-ex1)**2)/focus[i][0])+(((focus[i][1]-ex2)**2)/focus[i][1])
chi_score

np.float64(4765.001499277434)